//
//  DataProvider.swift
//  CitizenshipQuiz
//
//  Created by Maxime Boulat on 4/19/19.
//  Copyright © 2019 Maxime Boulat. All rights reserved.
// 

import Foundation


let dataSource: [QuizItem] = [
	QuizItem(question: "What is the supreme law of the land?",
			 answer: "the Constitution"),
	QuizItem(question: "What does the Constitution do?",
			 answer: "Sets up / defines the govt, protects basic rights of Americans"),
	QuizItem(question: "The idea of self govt is in the first three words of the Constitution. What are these words?",
			 answer: "We the People"),
	QuizItem(question: "What is an amendment?",
			 answer: "A change to the Constitution"),
	QuizItem(question: "What do we call the first ten amendments to the Constitution?",
			 answer: "The Bill of Rights"),
	QuizItem(question: "What is one right or freedom from the First Amendment?",
			 answer: "speech"),
	QuizItem(question: "How many amendments does the Constitution have?",
			 answer: "27"),
	QuizItem(question: "What did the Declaration of Independence do?",
			 answer: "Announced our independence from Great Britain"),
	QuizItem(question: "What are two rights from the Declaration of Independence?",
			 answer: "Life, liberty, pursuit of happiness"),
	QuizItem(question: "What is freedom of religion?",
			 answer: "You can practice any religion, or no religion"),
	QuizItem(question: "What is the economic system in the United States?",
			 answer: "capitalist economy"),
	QuizItem(question: "What is the rule of law?",
			 answer: "no one is above the law"),
	QuizItem(question: "Name one branch or part of the government",
			 answer: "Congress"),
	QuizItem(question: "What stops one branch of the government from becoming too powerful",
			 answer: "Separation of powers"),
	QuizItem(question: "Who is in charge of the executive branch?",
			 answer: "the President"),
	QuizItem(question: "Who makes federal law?",
			 answer: "Congress (Senate + House of representatives)"),
	QuizItem(question: "What are the two parts of the US Congress?",
			 answer: "Senate + House of Respresentatives"),
	QuizItem(question: "How many US Senators are there?",
			 answer: "100"),
	QuizItem(question: "We elect a US Senator for how many years?",
			 answer: "6"),
	QuizItem(question: "Who is one of your state's US Senator now?",
			 answer: "Diane Feinstein"),
	QuizItem(question: "The House of Representatives has how many voting members",
			 answer: "435"),
	QuizItem(question: "We elect a US Representative for how many years",
			 answer: "2"),
	QuizItem(question: "Name your representative",
			 answer: "Scott Peters (52nd district)"),
	QuizItem(question: "Who does a US Senator represent?",
			 answer: "All the people in the State"),
	QuizItem(question: "Why do some states have more representatives than others?",
			 answer: "because they have more people"),
	QuizItem(question: "We elect a President for how many years?",
			 answer: "4"),
	QuizItem(question: "In what month do we vote for President?",
			 answer: "November"),
	QuizItem(question: "What is the name of the President of the United States now?",
			 answer: "Donald Trump"),
	QuizItem(question: "What is the name of the Vice President of the United States now?",
			 answer: "Michael Pence"),
	QuizItem(question: "If the President can no longer serve, who becomes President?",
			 answer: "the Vice President"),
	QuizItem(question: "If both the President and the Vice President can no longer serve, who becomes President?",
			 answer: "the Speaker of the House"),
	QuizItem(question: "Who is the Commander in Chief of the military?",
			 answer: "the President"),
	QuizItem(question: "Who signs bills to become laws?",
			 answer: "the President"),
	QuizItem(question: "Who vetoes bills?",
			 answer: "the President"),
	QuizItem(question: "What does the President's cabinet do?",
			 answer: "advises the President"),
	QuizItem(question: "What are two Cabinet-level positions?",
			 answer: "Secretary of Defense, Secretary of Education"),
	QuizItem(question: "What does the judicial branch do?",
			 answer: "reviews laws, resolves dispute, decide if a law goes against the constitution"),
	QuizItem(question: "What is the highest court in the United States?",
			 answer: "the Supreme Court"),
	QuizItem(question: "How many justices are on the Supreme Court?",
			 answer: "9"),
	QuizItem(question: "Who is the Chief Justice of the United States?",
			 answer: "John Roberts"),
	QuizItem(question: "Under our Constitution, some powers belongs to the federal government. What is one power of the federal government?",
			 answer: "to make treaties, to declare war, to print money"),
	QuizItem(question: "Under our Constitution, some powers belong to the states. What is one power of the states?",
			 answer: "Provide schooling and education, provide protection (police)"),
	QuizItem(question: "Who is the governor of your state now?",
			 answer: "Gavin Newsom"),
	QuizItem(question: "What is the capital of your state?",
			 answer: "Sacramento"),
	QuizItem(question: "What are the two major political parties in the United States?",
			 answer: "Democratic and Republican"),
	QuizItem(question: "What is the political party of the President now?",
			 answer: "Republican"),
	QuizItem(question: "What is the name of the Speaker of the House of Representatives now?",
			 answer: "Nancy Pelosi"),
	QuizItem(question: "There are 4 amendments to the Constitution about who can vote, describe one of them?",
			 answer: "Citizens eighteen and older"),
	QuizItem(question: "What is one responsibility that is only for United States citizens?",
			 answer: "serve on a jury"),
	QuizItem(question: "Name one right only for United States citizens?",
			 answer: "vote in a federal election"),
	QuizItem(question: "What are two rights of everyone living in the United States?",
			 answer: "Freedom of expression, right to bear arms, freedom of religion, freedom of speech"),
	QuizItem(question: "What do we show loyalty to when we say the Pledge of Allegiance?",
			 answer: "the United States, the flag"),
	QuizItem(question: "What is one promise that you make when you become a United States citizen?",
			 answer: "give up loyalty to other countries, obey the laws of the United States, serve the nation"),
	QuizItem(question: "How old do citizens have to be to vote for the President?",
			 answer: "18 and older"),
	QuizItem(question: "What are two ways that Americans can participate in their democracy?",
			 answer: "Vote, give an elected official your opinion on an issue"),
	QuizItem(question: "When is the last day you can send in federal income tax forms?",
			 answer: "April 15th"),
	QuizItem(question: "When must all men register for the Selective Service?",
			 answer: "at age 18, between 18 and 26"),
	QuizItem(question: "What is one reason colonists came to America?",
			 answer: "freedom, economic opportunity, escape persecution"),
	QuizItem(question: "Who lived in America before the Europeans arrived?",
			 answer: "Native Americans"),
	QuizItem(question: "What group of people was taken to America and sold as slaves?",
			 answer: "Africans"),
	QuizItem(question: "Why did the colonists fight the British?",
			 answer: "Because of high taxes (taxation without representation), because the British army stayed in their houses (boarding, quartering)"),
	QuizItem(question: "Who wrote the Declaration of Independance?",
			 answer: "Thomas Jefferson"),
	QuizItem(question: "When was the Declaration of Independence adopted?",
			 answer: "July 4th 1776"),
	QuizItem(question: "There were 13 original states, name three?",
			 answer: "New Hampshire, Massachussets, Rhode Island, Connecticut, New York, New Jersey, Pennsylvenia, Delaware, Maryland, Virginia, North Carolina, South Carolina, Georgia"),
	QuizItem(question: "What happened at the Constitutional Convention?",
			 answer: "The Founding Fathers wrote he Constitution"),
	QuizItem(question: "When was the Constitution written?",
			 answer: "1787"),
	QuizItem(question: "The Federalist papers supported the Passage of the US Constitution, name one of the writers?",
			 answer: "James Madison, Alexander Hamilton"),
	QuizItem(question: "What is one thing that Benjamin Franklin is famous for?",
			 answer: "first Postmaster General of the United States, (one of the most influential Founding Father of the United States)"),
	QuizItem(question: "Who is the 'Father of Our Country'?",
			 answer: "George Washington"),
	QuizItem(question: "Who was the first President?",
			 answer: "George Washington"),
	QuizItem(question: "What territory did the United States buy from France in 1803?",
			 answer: "the Louisiana Territory"),
	QuizItem(question: "Name one war fought by the United States in the 1800s?",
			 answer: "Civil War"),
	QuizItem(question: "Name the US war between the North and the South?",
			 answer: "the Civil War"),
	QuizItem(question: "Name one problem that led to the Civil War?",
			 answer: "slavery"),
	QuizItem(question: "What was one important thing that Abraham Lincoln did?",
			 answer: "preserved the Union, freed the slaves, led the United States during the Civil War"),
	QuizItem(question: "What did the Emancipation Proclamation do?",
			 answer: "freed the slaves"),
	QuizItem(question: "What did Susan B Anthony do?",
			 answer: "fought for women's rights"),
	QuizItem(question: "Name one war fought by the United States in the 1900s?",
			 answer: "Word War I, II, Korean War, Vietname war, Gulf War"),
	QuizItem(question: "Who was the President during World War I?",
			 answer: "Woodrow Wilson"),
	QuizItem(question: "Who was the President during the Great Depression and World War II?",
			 answer: "Franklin Roosevelt"),
	QuizItem(question: "Who did the United States fight during World War II?",
			 answer: "Japan, Germany, Italy"),
	QuizItem(question: "Before he was President, Eisenhower was a general. What was was he in?",
			 answer: "World War II"),
	QuizItem(question: "During the Cold War, what was the main concern of the United States?",
			 answer: "Communism"),
	QuizItem(question: "What movement tried to end racial discrimination?",
			 answer: "civil rights movement"),
	QuizItem(question: "What did Martin Luther King Jr. do?",
			 answer: "fought for civil rights"),
	QuizItem(question: "What major event happened om September 11 2001, in the United States?",
			 answer: "Terrorists attacked the United States"),
	QuizItem(question: "Name one American Indian tribe in the United States?",
			 answer: "Cherokee"),
	QuizItem(question: "Name one of the longest rivers in the United States?",
			 answer: "Mississipi, Missouri"),
	QuizItem(question: "What ocean is on the West Coast of the United States?",
			 answer: "Pacific ocean"),
	QuizItem(question: "What ocean is on the East Coast of the United States?",
			 answer: "Atlantic ocean"),
	QuizItem(question: "Name one US territory?",
			 answer: "Puerto Rico, US Virgin Islands"),
	QuizItem(question: "Name one state that borders Canada?",
			 answer: "New York"),
	QuizItem(question: "Name one state that borders Mexico?",
			 answer: "California, Texas, Arizona"),
	QuizItem(question: "What is the capital of the United States?",
			 answer: "Washington DC"),
	QuizItem(question: "Where is the Statue of Liberty?",
			 answer: "New York harbor"),
	QuizItem(question: "Why does the flag have 13 stripes?",
			 answer: "Because there are 13 original colonies"),
	QuizItem(question: "Why does the flag have 50 stars?",
			 answer: "Because there is one star for each state"),
	QuizItem(question: "What is the name of the national anthem?",
			 answer: "The Star-Spangled Banner"),
	QuizItem(question: "When do we celebrate Independence Day?",
			 answer: "July 4th"),
	QuizItem(question: "Name two national US holidays?",
			 answer: "New Years Day, Labor Day, Thanksgiving")
]

class DataProvider: DataProviding {
	
	private var deck: [QuizItem] = []
	
	func resetDeck() {
		deck = dataSource
	}
	
	func getPair() -> QuizItem? {
		
		if !deck.isEmpty {
			let randomIndex = Int.random(in: 0..<deck.count)
			
			print("picked random index: \(randomIndex)")
			let item = deck.remove(at: randomIndex)
			
			print("count remaining: \(deck.count)")
			return item
		}
		else {
			print("empty deck")
			return nil
		}
	}
	
}
